// <auto-generated />
namespace FinancialPortal.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TransactionCreatedDatetoTransactionDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TransactionCreatedDatetoTransactionDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201912162103003_TransactionCreatedDate-to-TransactionDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
